name: build
on:
  workflow_dispatch:
  push: {branches: [main]}
  pull_request: {branches: [main]}
jobs:
  conda:
    defaults: {run: {shell: 'bash -el {0}'}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: prefix-dev/rattler-build-action@v0.2.37
      with: {recipe-path: recipe.yaml}
    - if: github.ref == 'refs/heads/main'
      name: conda upload -c ccpi
      run: >
        rattler-build upload anaconda ./output/*/*.conda -f
        -o ccpi -c main -a ${{ secrets.CCPI_CONDA_TOKEN }}
    - if: github.ref == 'refs/heads/main'
      name: conda upload -c tomography.stfc.ac.uk/conda
      working-directory: output
      run: |
        echo '${{ secrets.STFC_SSH_KEY }}' > ./key
        chmod 600 ./key
        rsync -e 'ssh -o StrictHostKeyChecking=no -i ./key' -R */*.conda '${{ secrets.STFC_SSH_HOST }}:${{ secrets.STFC_SSH_CONDA_DIR }}'
        ssh -o StrictHostKeyChecking=no -i ./key ${{ secrets.STFC_SSH_HOST }} \
          'bash -lic "conda index --bz2 --zst --run-exports --channeldata --rss -n ccpi ${{ secrets.STFC_SSH_CONDA_DIR }}"'
